[package]
name = "router"
version = "0.1.0"
edition = "2021"

[dependencies]
kube.workspace = true
context.workspace = true
anyhow.workspace = true
axum.workspace = true

[dev-dependencies]
tokio.workspace = true
reqwest.workspace = true
