[package]
name = "router"
version = "0.1.12"
edition = "2021"

[dependencies]
anyhow.workspace = true
axum.workspace = true
tracing.workspace = true
logger.workspace = true

[dev-dependencies]
tokio.workspace = true
reqwest.workspace = true

