[workspace]
members = ["common/version","common/*","crates/*"]
resolver = "2"

[workspace.dependencies]
common = { path = "./common/version" }
logger = { path = "./common/logger" }
kube = { path = "./common/kube" }
