version = "Two"
comment_width = 120
normalize_comments = true
normalize_doc_attributes = true
group_imports = "StdExternalCrate"
format_code_in_doc_comments = true
format_macro_bodies = true
format_macro_matchers = true
unstable_features = true
condense_wildcard_suffixes = true
wrap_comments = true
newline_style = "Unix"
use_field_init_shorthand = true
use_try_shorthand = true
imports_granularity = "Crate"

