[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
chrono.workspace = true
axum.workspace = true
reqwest.workspace = true
thiserror.workspace = true
tracing.workspace = true
anyhow.workspace = true
serde_json.workspace = true
