[package]
name = "kube"
version = "0.1.0"
edition = "2021"

[dependencies]
common.workspace = true
logger.workspace = true
kube-runtime = { version = "0.92.1", package = "kube", features = ["runtime", "derive"] }
k8s-openapi = { version = "0.22.0", features = ["latest"] }
