[package]
name = "context"
version = "0.1.0"
edition = "2021"

[dependencies]
kube.workspace = true
config.workspace = true
regex.workspace = true
anyhow.workspace = true
sqlx.workspace = true
tracing.workspace = true
chrono.workspace = true
