[package]
name = "boot"
version = "0.1.0"
edition = "2021"

[dependencies]
common.workspace = true
logger.workspace = true
router = { path = "../router" }
serde = { version = "1.0", features = ["derive"] }
